name: Deploy to GitHub Pages and Upload New Posts to Supabase

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build site
        env:
          BASE_PATH: '/D4r3d3vil.github.io'
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/'

  check_and_upload:
    needs: build_site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 2
      - name: Check for new posts
        id: check_new_files
        run: |
          new_files=$(git diff --name-only HEAD~1 HEAD | grep 'uploads/pages/' || echo "")
          echo "New files: $new_files"
          echo "::set-output name=new_files::$new_files"

      - name: Upload new posts to Supabase
        if: ${{ steps.check_new_files.outputs.new_files != '' }}
        run: |
          for file in ${{ steps.check_new_files.outputs.new_files }}
          do
            curl -X POST 'https://njjzkksmwdmmrlfmafwe.supabase.co/rest/v1/posts' \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qanpra3Ntd2RtbXJsZm1hZndlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyMjg2NDkxMiwiZXhwIjoyMDM4NDQwOTEyfQ.DKmVtJ8mNDAJx-O_ACnPkO56XQOqoGflcVUtKBru620" \
            -H "Authorization: Bearer SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d '{ "name": "$file"}'
          done

  deploy:
    needs: [build_site, check_and_upload]
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
